//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_PrintingServer_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationLog
    {
        public int Id { get; set; }
        public string ActionName { get; set; }
        public string JsonObject { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
