//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_PrintingServer_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDetails
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string UUID { get; set; }
        public string OS { get; set; }
        public string Name { get; set; }
        public string Architecture { get; set; }
        public string PosType { get; set; }
        public string PosDestination { get; set; }
        public string PosHost { get; set; }
        public string PosPort { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string pos_userName { get; set; }
        public string pos_password { get; set; }
        public string company_uin { get; set; }
        public string pos_articles_URL { get; set; }
    }
}
